# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a1abb20a943399ac514a082251f0b9eff80e98695234f1188f11df7679f4f48f2bfbbce78282c0f3e76a447cef3576201c540949ab639d16da2dbdedaf51d0f6

test:
  secret_key_base: 1ddb8ecd915c598c4f2a397f72ace0f6f9c8fd54307b1866c63869967b86e24e925bfd46bc22688aac8daae77da74e77e23ffa940e37d6df6eb14ca03274060c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
